### ISSUE TITLE
ERROR NAME NOT RESOLVED

### ISSUE THREAD

**Issue by steven-tib** [juliancwirko/s-chat-app#7]
Hi, I'm getting this error after following your procedure to install schat (Saas).

`sockjs-0.3.4.js:854 GET https://https//www.simplechat.support/sockjs/info?cb=kjctglky_3 net::ERR_NAME_NOT_RESOLVED
`

any clue ? thank you

**Comment by juliancwirko** [comment]
Hi, as you can see: `https://https//` I guess this is the problem. You have probably wrong url in your config.

try with `hostName: 'www.simplechat.support'`, and not `hostName: 'https//www.simplechat.support'`

**Comment by steven-tib** [comment]
Great, it works ! thank you
